export const FUND_DISTRIBUTION_COLUMNS: any;
export const FUND_DISTRIBUTION_VISIBLE_COLUMNS: any;
export const FUND_DISTRIBUTION_FIELDS_MAPPINGS: any;
export const FUND_DISTRIBUTION_COLUMN_MAPPING: any;
