export const CommandList: any;
export const HasCommand: any;
export const expandAllSections: any;
export const collapseAllSections: any;
export const checkScope: any;
export const defaultKeyboardShortcuts: any;
export const keyboardShortcutNames: any;
export const importShortcuts: any;
export const renameShortcutLabels: any;
