export const SEARCH_PARAMETER: 'query';
export const SEARCH_INDEX_PARAMETER: 'qindex';
export const OFFSET_PARAMETER: 'offset';
export const LIMIT_PARAMETER: 'limit';
export const SORTING_PARAMETER: 'sorting';
export const SORTING_DIRECTION_PARAMETER: 'sortingDirection';
export const ASC_DIRECTION: 'ascending';
export const DESC_DIRECTION: 'descending';
export const DATE_RANGE_FILTER_FORMAT: 'YYYY-MM-DDTHH:mm:ss.SSS';
