name: Centralized workflow
on:
  - push
  - pull_request
  - workflow_dispatch

jobs:
  ui:
    uses: folio-org/.github/.github/workflows/ui.yml@v1
    # Only handle push events from the main branch or tags, to decrease PR noise
    if: github.ref_name == github.event.repository.default_branch || github.event_name != 'push' || github.ref_type == 'tag'
    secrets: inherit
    with:
      # tsc instead of jest, but easiest to run it in the same manner
      jest-enabled: true
      jest-test-command: yarn test
      sonar-sources: .
      compile-translations: false
      generate-module-descriptor: false
